### ISSUE TITLE
[Bug] Reroll sometimes spawns player in the same position

### ISSUE THREAD

**Issue by CalaMariGold** [SmashingMods/Reroll#14]
Reroll distance was set to 1000. Hop in Trepidation and reroll at least 10 times and it should happen.

**Comment by Dark-Arcana** [comment]
Fixed in 74dfc2336f41bd3ba7a4ccae6e43845797386393 . This one was interesting, but it shouldn't ever happen again. 😅 let me know if that's incorrect and it does happen again.
