### ISSUE TITLE
[Bug] Reroll always spawns player in the same dimension

### ISSUE THREAD

**Issue by CalaMariGold** [SmashingMods/Reroll#15]
I have "reroll dimension" set to false and override dimension set to -1, but its still spawning me in the same dimension. For example rerolling in the erebus spawns me in the erebus when it should be in the nether.

**Comment by Dark-Arcana** [comment]
Fixed in 74dfc2336f41bd3ba7a4ccae6e43845797386393 . Override dimension *should* work period now. I tested a lot. But your mile may vary. Let me know if you run into this issue again.
