### ISSUE TITLE
Reroll on Death still occurs when set to false

### ISSUE THREAD

**Issue by CalaMariGold** [SmashingMods/Reroll#16]
# Reroll players if they die to simulate a hardcore experience. [default: false]
    B:"Reroll On Death [Hardcore Mode]"=false

Dying in a survival world still seems to trigger this

**Comment by Dark-Arcana** [comment]
LOOOOOL I had "true" hardcoded into it for testing.

Fixed in 17054cce49f4f3519e20e1ac4104a5e24d49c79d
