### ISSUE TITLE
Rerolling doesn't reset the player being on fire

### ISSUE THREAD

**Issue by CalaMariGold** [SmashingMods/Reroll#17]
Rerolling while on fire will mean you're still on fire and take damage after rerolling

**Comment by Dark-Arcana** [comment]
This is odd. I've set it to extinguish the player and put their health back to 20. Though I should set it to their potential max health if there is such a thing.

In either case, I'll change it to extinguish first and then set health in that order. And to reset that after the teleport just in case.

**Comment by Timiryazev** [comment]
Testing this, it seems to be an issue if you reroll while IN fire. Is it possible you're extinguishing before teleporting, and not after?

**Comment by Dark-Arcana** [comment]
Yeah that's exactly it. I've changed the order to account for it.

**Comment by Dark-Arcana** [comment]
Fixed in 17054cce49f4f3519e20e1ac4104a5e24d49c79d

Note that severe lag can cause it to still happen.
