### ISSUE TITLE
Dice rerolls the player twice

### ISSUE THREAD

**Issue by CalaMariGold** [SmashingMods/Reroll#18]
Using the dice rerolls the player twice, or at least, puts out the chat message twice.

**Comment by Dark-Arcana** [comment]
It's rerolling twice, can confirm. Let me find a fix.

**Comment by Dark-Arcana** [comment]
It happens twice because it's triggering the event on both client and server (integrated server). So I've added a check to see if the event is on the server and then to only do it if it's not.

**Comment by Dark-Arcana** [comment]
Fixed in 17054cce49f4f3519e20e1ac4104a5e24d49c79d
